Generate RTS price data
NREL-SIIP/HybridSystemsSimulations.jl pull request #1
Opened 2023-02-03 00:30 UTC by rodrigomha

2023-02-06 15:46 UTC, jd-lara commented on scripts/get_templates.jl
> +        DeviceModel(Line, StaticBranchUnbounded, duals=[NetworkFlowConstraint]),
If this is unbounded then the duals are always 0.0

2023-02-06 15:47 UTC, jd-lara commented on scripts/main_test.jl
> +using Pkg
should we call this script price generation?

2023-02-06 15:48 UTC, jd-lara requested changes
The file organization needs a little bit of a change to separate the functions used for price generation and the script.

2023-02-09 01:16 UTC, rodrigomha commented
@jd-lara @sourabhdalvi 

Here are the main scripts. I need to figure out how to access the forecast to export it and that will complete this PR.

2023-02-10 21:01 UTC, rodrigomha commented
@jd-lara This is ready for an additional review

2023-02-13 19:59 UTC, jd-lara approved these changes

2023-02-13 19:59 UTC, merged